# Generated by Django 5.2.6 on 2025-09-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car_DB",
            fields=[
                ("car_Brand", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=10)),
                ("safety_Features", models.CharField(max_length=50)),
                ("car_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("car_Price", models.IntegerField()),
            ],
        ),
    ]
